# .circleci/config.yml
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.3.0"
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout
      - run:
          name: Run Deskstrap
          command: |
            ./bin/deskstrap.sh
      - run:
          name: list home dir
          command: |
            ls -al ~


      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
